// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Comment struct {
	ID        string `json:"id"`
	PostID    string `json:"postId"`
	Text      string `json:"text"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	CreatedAt       string     `json:"createdAt"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}
